server:
  port: 8080
spring:
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: "*"

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp
    password: LMjahd@0789
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
Messages:
  Hello: Hey im from Dev

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp-prod
    password: LMjahd@0789
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
Messages:
  Hello: Hey im from prod